variant: ndg3
value-type: year-on-year-growth
values:
  ip:
    elective: [0.999, 1.0271]
    non-elective: [0.9963, 1.0268]
    maternity: [1, 1]
  op:
    first: [1.0002, 1.0487]
    followup: [1.0002, 1.0487]
    procedure: [1.0002, 1.0487]
  aae:
    ambulance: [0.9946, 1.0352]
    walk-in: [0.9946, 1.0352]
